---
title: "Performances"
---

<br>

### Performances

#### 2023
Bass Soloist, *Te Deum* (Dvořák), Barnard-Columbia Chorus and the Academic Choir of Gdynia Maritime University (Apr/Jun 2023)

#### 2022
Bass Soloist, *Missa solemnis*, Barnard-Columbia Chorus (Dec 2022) [[Link]](https://www.youtube.com/live/cks6NH_yT8g?feature=share&t=6807)

Solo Voice Recital, Columbia University (May 2022) [[Link](https://youtu.be/Vk0wRwFLRG4)]

Bass Soloist, *Mass in D major* (Dvořák), Barnard-Columbia Chorus (Apr 2022) [[Link]](https://www.youtube.com/live/iS-Zl46HlcI?feature=share&t=3079)

#### 2021

Chorus Member, *All-Night Vigil*, Barnard-Columbia Chorus (Dec 2021) [[Link](https://youtu.be/4Jr7f69howQ?t=2070)]

#### 2019

Bass Soloist, *Messiah*, Barnard-Columbia Chorus (Dec 2019) [[Link](https://youtu.be/nNUb-7enq0I?t=791)]

Grandpa Moss, *The Tender Land* (scene), Columbia New Opera Workshop (Nov 2019)

Schlendrian, *Schweigt stille, plaudert nicht* (scene), Columbia New Opera Workshop (Nov 2019)

Raphael, *The Creation*, Barnard-Columbia Chorus (Apr 2019) [[Link](https://youtu.be/us_GsdnoXMo?t=3570)]

Sarastro, *Die Zauberflöte*, Columbia New Opera Workshop (Apr 2019) [[Link](https://youtu.be/X3zzSkea458?t=4057)]

#### 2018

Invited singer, *In the Mouth of the Wolf*, Rivertown Film Socieity (Dec 2018)

Bass Soloist, *Magnificat (BWV 243)* Barnard-Columbia Chorus (Dec 2018)

Guglielmo, *Cosi fan tutte* (scene), Columbia New Opera Workshop (Nov 2018) [[Link](https://youtu.be/u3IzRAvslsw?t=277)]

Leporello, *Don Giovanni* (scene), Columbia New Opera Workshop (Nov 2018) [[Link](https://youtu.be/u3IzRAvslsw?t=3358)]

Bass Soloist, *Messa da Requiem* (Verdi), Barnard-Columbia Chorus and The Choir of the University of Modena and Reggio Emilia (Apr 2018)

#### 2017

Simon, *Judas Maccabeus*, Barnard-Columbia Chorus (Dec 2017) [[Link](https://youtu.be/aqBeiw3uw50?t=1311)]

Leporello, *Don Giovanni* (scene), Columbia New Opera Workshop (Nov 2018) [[Link](https://youtu.be/h2jIbs2sRjI?t=1809)]

Dual Voice Recital with Harry Bickford, Barnard College (May 2017)

Bass Soloist, *Great Mass in C minor (K. 427)*, Barnard-Columbia Chorus and Choeur Universitaire de Lausanne (Apr 2017)

Elijah, *Elijah*, Barnard-Columbia Chorus (Mar 2017)

Invited singer, *In the Mouth of the Wolf*, Film Forum NYC (Feb 2017)

#### 2016

Bass Soloist, *Mass in B minor (BWV 232)*, Barnard-Columbia Chorus (Dec 2016)

Buff, *Der Schauspieldirektor*, Columbia New Opera Workshop (Dec 2016)

Sarastro, *Die Zauberflöte* (in English), Columbia Bach Society (Apr 2016)

#### 2015

Bass Soloist, *Messiah*, Barnard-Columbia Chorus (Dec 2015)

Samuel, *Saul and the Witch at Endor*, Columbia New Opera Workshop (Nov 2015)

Buff, *Der Schauspieldirektor*, Peabody Opera Department (Apr 2015)

Chorus Member, *Die Entfürung aus dem Serail*, Peabody Opera Department (Mar 2015)

#### 2014

Solo Voice Recital, Mount Vernon United Methodist Church (May 2014) [[Link](https://www.youtube.com/watch?v=8CEXxKezI1A&list=PLqaVpiVpL23szCMiyHNql-DcJvBp_ysEB)]

Peter, *Now We Are Met* (debut), Peabody Opera Department (Apr 2014)

#### 2013

Signor Deluso, *Signor Deluso* (scene), Peabody Opera Department (May 2013)

Count Almaviva, *Le Nozze di Figaro* (scene), Peabody Opera Department (Nov 2013)

Antonio, *Le Nozze di Figaro* (scene), Peabody Opera Department (Nov 2013)

#### 2012 and before

Dr. Caius, *Die lustigen Weiber von Windsor* (scene), Peabody Opera Department (May 2012)

Chorus Member, *Les Mamelles de Tiresias*, Peabody Opera Department (Apr 2011)

Chorus Member, *L'enfant et les sortileges*, Peabody Opera Department (Apr 2011)

Chorus Member, *Manon*, Peabody Opera Department (Nov 2010)

<br>

### Awards

Second Place, NATS MD/DC District Auditions, Classical Singing Continuing Education Men category (Feb 2015)

Homewood Arts Certificate for voice recital project (May 2014)

First place, National Association of Teachers of Singing (NATS) MD/DC District Auditions, Classical Singing Senior Men category (Feb 2014)

Third place, NATS Mid-Atlantic Regional Auditions, Classical Singing Sophomore Men category (Apr 2012)

Second place, NATS MD/DC District Auditions, Classical Singing Sophomore Men category (Feb 2012)

First place, NATS MD/DC District Auditions, Classical Singing Freshman Men category (Feb 2011)

<br>

### Reviews

Columbia Spectator (Dec 2019) [[Link](https://www.columbiaspectator.com/arts-and-entertainment/2019/11/18/columbia-nows-repertory-scenes-are-a-must-see-for-opera-laypeople/)]

Bwog (Apr 2019) [[Link](https://bwog.com/2019/04/the-sun-shines-down-on-the-new-opera-workshops-magic-flute/)]

Columbia Spectator (Dec 2018) [[Link](https://www.columbiaspectator.com/arts-and-entertainment/2018/12/05/new-opera-workshops-innovative-repertory-is-opera-for-the-21st-century/)]

Bwog (Nov 2018) [[Link](http://bwog.com/2018/11/30/o-welche-lust-a-repertory-smorgasbord-by-the-new-opera-workshop/)]

Columbia Spectator (Dec 2017) [[Link](http://columbiaspectator.com/arts-and-entertainment/2017/12/01/new-opera-workshops-spirited-repertory-strikes-a-chord/)]
