---
title: "Personal"
---

<br>

Welcome to the personal section of my website! This portion of the website is dedicated to the various eclectic interests that I have outside of research.

<br>

### Carnegie Hall

As a Carnegie Hall Music Ambassador, I give [guided tours](https://www.carnegiehall.org/Visit/Tour) of Carnegie Hall during its regular season. Weekly tour schedules can be found [here](https://www.carnegiehall.org/Visit/Tour/Public-Walk-In-Tours).

In addition, Carnegie Hall provides [$10 student tickets](https://www.carnegiehall.org/en/Events/Discount-Programs/Student-Tickets) to select performances, and [$20 tickets](https://www.carnegiehall.org/en/Support/Membership/Notables/20-Tickets) to all Carnegie Hall presentations for individuals part of the Notables program. Anyone under the age of 40 can join the Notables program, and annual memberships start at only $20. If you like classical music, this is one of the best deals in town!

<br>

### Vocal Performances

I am also an active singer myself, and study voice with [Dr. Robert Osborne](https://www.vassar.edu/faculty/roosborne/). I engage in several performances per semester, including both operatic and oratorio works. Below are some links to select performances:

[Senior Voice Recital](https://www.youtube.com/watch?v=8CEXxKezI1A&list=PLqaVpiVpL23szCMiyHNql-DcJvBp_ysEB) (2014) <br>
Simon, Handel's [Judas Maccabeus](https://youtu.be/aqBeiw3uw50?t=1311) (2017) <br>
Bass soloist, Haydn's [The Creation](https://youtu.be/us_GsdnoXMo?t=3570) (2019) <br>
Sarastro, Mozart's [The Magic Flute](https://youtu.be/X3zzSkea458?t=4057) with the Columbia New Opera Workshop (2019)

<br>

### Food and Beer Reviews

I am a big fan of writing reviews. Of the various things that I have attempted, two things I have kept up with are Yelp and BeerAdvocate. You can find my restaurant reviews [here](https://www.yelp.com/user_details_reviews_self?userid=8oDB6mhtccdTy3O66PmxhA) and my beer reviews [here](https://www.beeradvocate.com/user/beers/?ba=Profundobaso). The beer reviews are updated quite frequently (perhaps even more frequently than this website...)