---
title: "Repertoire"
---

<br>

### English
B. Andersson – Anthem (from *Chess*)

S. Barber – With rue my heart is laden

J. Duke – I ride the great black horses

G. Finzi – Rollicum-Rorum

Gilbert & Sullivan – Major-General’s Song (from *The Pirates of Penzance*)

G. Handel – But who may abide the day of his coming? (from *Messiah*)

G. Handel – The people that walked in darkness (from *Messiah*)

G. Handel – Why do the nations so furiously rage together? (from *Messiah*)

G. Handel – The trumpet shall sound (from *Messiah*)

G. Handel – Honor and arms (from *Samson*)

G. Handel – Pious orgies, pious airs (from *Judas Maccabaeus*)

G. Handel – Arm, arm, ye brave! (from *Judas Maccabaeus*)

G. Handel – Rejoice, oh Judah! (from *Judas Maccabaeus*)

J. Haydn – Now heav’n in fullest glory shone (from *The Creation*)

J. Haydn – Roaming in foaming billows (from *The Creation*)

J. Kern – Ol’ Man River (from *Showboat*)

F. Mendelssohn – For the mountains shall depart (from *Elijah*)

F. Mendelssohn – Is not His word like a fire? (from *Elijah*)

F. Mendelssohn – It is enough (from *Elijah*)

F. Mendelssohn – Lord God of Abraham (from *Elijah*)

H. Purcell – Saul and the Witch at Endor

N. Rorem – Look Down, Fair Moon

N. Rorem – To the Willow-tree

C. Schönberg – Stars (from *Les Misérables*)

L. Simon – Lily’s Eyes (from *The Secret Garden*)

M.T. Thomas - At Ship's Helm

M.T. Thomas - Grace

R. Vaughan Williams – Bright is the Ring of Words

R. Vaughan Williams – Let Beauty Awake

R. Vaughan Williams – The Vagabond

R. Vaughan Williams – Whither must I Wander

<br>


### Italian
F. Durante – Danza, danza, fanciulla gentile

G. Giordani – Caro mio ben

W. Mozart – Ah, pietà! Signori miei! (from *Don Giovanni*)

W. Mozart – Là ci darem la mano (from *Don Giovanni*)

W. Mozart – La vendetta (from *Le Nozze di Figaro*)

W. Mozart – Madamina! Il catalogo ѐ questo (from *Don Giovanni*)

W. Mozart – Non più andrai (from *Le Nozze di Figaro*)

W. Mozart – Se vuol ballare (from *Le Nozze di Figaro*)

G. Rossini – La calunnia (from *Il Barbiere di Siviglia*)

<br>


### German
J.S. Bach – Hat man nicht mit seinen Kindern (from *Schweigt stille, plaudert nicht*)

J. Brahms – Wie Melodien zieht es mir

F. Mendelssohn – Da das die Apostel hörten (from *Paulus*)

F. Mendelssohn – Gott, sei mir gnädig (from *Paulus*)

F. Mendelssohn – Ich danke dir, Herr, mein Gott (from *Paulus*)

F. Mendelssohn – Vertilge sie, Herr Zebaoth (from *Paulus*)

W. Mozart – In Diesen Heil’gen Hallen (from *Die Zauberflöte*)

W. Mozart – O Isis und Osiris (from *Die Zauberflöte*)

W. Mozart – O, wie will ich triumphiren (from *Die Entführung aus dem Serail*)

W. Mozart – Solche hergelaufne Laffen (from *Die Entführung aus dem Serail*)

O. Nicolai – Als Büblein klein (from *Die lustigen Weiber von Windsor*)

J. Reichardt – Gott (from *Faust*)

F. Schubert – An die Musik

F. Schubert – Die Forelle

F. Schubert – Die Krähe

F. Schubert - Erlkönig

F. Schubert – Rastlose Liebe

F. Schubert – Wanderers Nachtlied II

R. Wagner – Leb’ wohl (from *Die Walküre*)

R. Wagner – O du mein holder Abendstern (from *Tannhäuser*)

H. Wolf - Fussreise

H. Wolf – Verborgenheit

<br>


### French
G. Bizet – Votre toast, je peux vous le render (from *Carmen*)

C. Gounod – Le veau d’or (from *Faust*)

R. Hahn – Si mes vers avaient des ailes

C. Saint-Saëns – Danse Macabre

G. Fauré – Clair de lune

<br>


### Russian
P. Tchaikovsky – King Rene’s Aria (from *Iolanta*)

P. Tchaikovsky – Don Juan’s Serenade

<br>


### Latin
J.S. Bach – Quoniam tu solus sanctus (from *Mass in B minor*)

J.S. Bach – Quia fecit mihi magna (from *Magnificat*)

L. Beethoven – Missa solemnis

A. Dvořák – Te Deum

G. Verdi – *Messa da Requiem*

<br>


### Chinese
X. Liu – Red Bean Song

X. Xian – Ode to the Yellow River (from *Yellow River Cantata*)

X. Xian – Dialogue Song by the Yellow River (from *Yellow River Cantata*)