---
title: "Teaching"
---

<br>

Below includes a summary of my current and past teaching roles. For a more detailed description of my teaching activities, including student testimony, sample course materials, and my teaching statement, please take a look at my [teaching portfolio](https://blogs.cuit.columbia.edu/zh2263/).

<br>

### Columbia University
Spring 2023: Course Instructor, BC3017 Environmental Data Analysis

Spring 2023: Course Instructor, GR5015 Data Analysis for the Social Sciences

Fall 2022: Course Instructor, BC3017 Environmental Data Analysis

Fall 2022: Course Instructor, GR5010 Theory and Methodology for the Social Sciences

Spring 2022: Course Instructor, GR5015 Data Analysis for the Social Sciences

Fall 2021: Course Instructor, GR5010 Theory and Methodology for the Social Sciences

Fall 2019: Teaching Scholar, P8301 Atmospheric and Climate Science for Public Health

Spring 2019: Teaching Scholar, P8304 Public Health Impacts of Climate Change

Spring 2018: Teaching Scholar, P8304 Public Health Impacts of Climate Change

Spring 2017: Teaching Scholar, P8304 Public Health Impacts of Climate Change

<br>

### Johns Hopkins Bloomberg School of Public Health
4th Quarter 2015: Teaching Assistant, PH.140.624 Statistical Methods in Public Health IV

3rd Quarter 2015: Teaching Assistant, PH.140.623 Statistical Methods in Public Health III

3rd Quarter 2015: Teaching Assistant, PH.317.600 Introduction to the Risk Sciences

2nd Quarter 2014: Teaching Assistant, PH.140.622 Statistical Methods in Public Health II

1st Quarter 2014: Teaching Assistant, PH.140.621 Statistical Methods in Public Health I

<br>

### Johns Hopkins University
Fall 2014: Teaching Assistant, AS.280.345 Public Health Biostatistics

Spring 2014: Teaching Assistant, EN.550.211 Probability and Statistics for the Life Sciences

Spring 2014: Course Mentor, AS.020.152 General Biology II

Spring 2014: Course Designated Tutor, AS.280.350 Fundamentals of Epidemiology

Fall 2013: Teaching Assistant, EN.550.111 Statistical Analysis I

Fall 2013: Teaching Assistant, AS.020.153 General Biology Lab I

Fall 2013: Teaching Assistant, AS.280.345 Public Health Biostatistics

Fall 2013: Course Mentor, AS.020.151 General Biology I

Spring 2013: Teaching Assistant, EN.550.211 Probability and Statistics for the Life Sciences

Fall 2012: Teaching Assistant, AS.280.345 Public Health Biostatistics
